### ISSUE TITLE
skip sudo check?

### ISSUE THREAD

**Issue by Danfro** [luigi311/Readonly-Packager#2]
On a read only system, apt (or other packager) is not encouraged to be used at all. So the first check, suggesting a user to use `sudo`, is not useful when "preventing" the use of "sudo apt" in the next step. This part can be skipped in my opinion.

**Comment by luigi311** [comment]
Until a new method of checking for read only is set the script requires root as a user is not allowed to write to / to check if the system is read only or not. If there is another reliable method for checking for read only then we can remove the sudo check

**Comment by Danfro** [comment]
Ok, thanks for the explanation. Then of course in its current state this does make sense.

**Comment by luigi311** [comment]
I have removed the sudo check as i have updated the fs check function.

**Comment by Danfro** [comment]
Cool. Thanks. I will try the updated script too.

--
